services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: garage_mint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "search_path=grg_mint,public"]
