app:
  name: GarageMint API
  uploads:
    root: ${UPLOAD_ROOT:./uploads}                  # dosyalar buraya yazılacak
    base-url: ${UPLOAD_BASE_URL:http://localhost:8080/uploads}  # public URL

server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:gmdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop

      ddl-auto: update
    flyway:
      enabled: true

  management:
    endpoints:
      web:
        exposure:
          include: "health,info"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger
