spring:
  profiles:
    active: dev
  security:
    filter:
      dispatcher-types: REQUEST
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  management:
    endpoints:
      web:
        exposure:
          include: "health,info"

app:
  name: GarageMint API
  uploads:
    root: ${UPLOAD_ROOT:./uploads}
    base-url: ${UPLOAD_BASE_URL:http://localhost:8080/uploads}
  security:
    jwt:
      secret: ${JWT_SECRET:dev-super-secret-please-change-1234567890}
      access-exp-min: 60
      issuer: garagemint

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger

cors:
  allowed-origins: https://garagemint.com
