spring:
  datasource:
    url: jdbc:h2:mem:gmdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
